### ISSUE TITLE
Username mangling for ssh repos

### ISSUE THREAD

**Issue by xbao** [frost-nzcr4/find_forks#3]
Hello again,

I think I found an edge case (related to #2). 

The repo I was running `find_forks` against was https://github.com/tjerkw/Android-SlideExpandableListView.

The remote setup:

```
[11:09 am] ~/dev/Android-SlideExpandableListView (master) $ git remote -v
origin  git@github.com:tjerkw/Android-SlideExpandableListView.git (fetch)
origin  git@github.com:tjerkw/Android-SlideExpandableListView.git (push)
```

The error when I run `find_forks`:

```
[11:09 am] ~/dev/Android-SlideExpandableListView (master) $ python3 ../git/find_forks
git config --get remote.origin.url
Open https://api.github.com/repos/jerkw/Android-SlideExpandableListView/forks?per_page=100
Error: Not Found
git fetch --all
Fetching origin
There are no interesting forks
```

The username is `tjerkw` but the URL is attempting to access `jerkw`

Changing it to https fixes the problem:

```
[11:10 am] ~/dev/Android-SlideExpandableListView (master) $ git remote set-url origin https://github.com/tjerkw/Android-SlideExpandableListView.git
[11:10 am] ~/dev/Android-SlideExpandableListView (master) $ python3 ../git/find_forksgit config --get remote.origin.url
Open https://api.github.com/repos/tjerkw/Android-SlideExpandableListView/forks?per_page=100
<output omitted>
```

**Comment by frost-nzcr4** [comment]
I'll check it, thanks.

**Comment by frost-nzcr4** [comment]
Oh, it is copypaste error, `lstrip` and `rstrip` works as it should and removes matched chars. So `lstrip('git@github.com:')` removes any of these chars '`bcghimotu@.:`' from the left and consumes '`git@github.com:t`', then it get '`j`' and stops. I'll fix it later.
